server {
    listen 80;
    server_name pizzasich.online www.pizzasich.online;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
	return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name pizzasich.online www.pizzasich.online;

    root /usr/share/nginx/html;

    ssl_certificate /etc/letsencrypt/live/pizzasich.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pizzasich.online/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://172.17.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-SSL on;
    }
}
